# Generated by Django 3.1 on 2025-07-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='users',
            new_name='user',
        ),
    ]
